<a href="https://colab.research.google.com/github/kigit2017/FeatureSelection/blob/main/Featureselection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

- feature selection is important for our data analysis beacuse it plays a crucial role in selecting a subset of the most relevant and important features (variables) from your dataset for further analysis or modeling.

By selectin ng proper feature we can improve model performance, recduce overfitting and enhancw the interpretability of results.

Step-Step- guid for feature selection :
1. Define Your problem:
    - Clearly understand your problem statement and the goals of your analysis.
    - Determine wether your problem is a classification , egression , clustering or other typeof problem
2. Data Collection and Exploration:
    - EDA we have use
    - using summary statistics, visulization and data visulization library we have to explore and find the insights from the data.

3. Under stand your feature:
    - Gain an understanding of each feature's meaning, relevance, and potential impact on the target varaibles.
    - identify categorical, numerical and other types of features/.

4. Data preprocessing:
    - Handle missing values by imputation or removing the affected samples
    - Deal with outliers, noise, and data anaomalies
    - Encode categorical variables using techniques, one-hot encoding , label encoder, pd.get_dummies.
    - Scale or normalize numberical features if needed.

5. Correlation Analysis:
    - Analyze the correlation between features and the target varaibles to identify potential predictors.
    - Calculate and visualize correlations using methods like pearson correlation or heatmap.

6. Feature Selection Techniques
  - There several techniques for feature selection
    - <b> Filter method </b> : Select features based on statistical metrics like correlation, mutal information or chi-sqaure test
    - Embedded methods : Feature selection is integrated with model training , like LASSO regression or decision trees.
    - Dimensionality Reduction : Technique like PCA,(principal component analysis) can be used ot reduce the dimensionality of the data.



### k-percentile Method
This statistical mehtod used to select the most informative featires based on their distribution or importance score. This mehtod involves selection featires that fall within a certain percentile range of importance.






In [1]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier
iris = load_iris()
X,y = iris.data, iris.target



rf_clas = RandomForestClassifier(n_estimators=100, random_state=42)
rf_clas.fit(X,y)

RandomForestClassifier(random_state=42)

In [2]:
iris = load_iris()
X,y = iris.data, iris.target

In [3]:
# we will creat base random forest calssifier
rf_clas = RandomForestClassifier(n_estimators=100, random_state=42)
rf_clas.fit(X,y)

RandomForestClassifier(random_state=42)

In [4]:
# get feature improtance from the trained random fores
feat_imp = rf_clas.feature_importances_
# we will define the desire percentage range(percentile range)
percentile_r = (0, 50)


# calculate threshold importance value based on the percentile range
threshold = np.percentile(feat_imp, percentile_r[1])

# select feature that meet the threshold importance
selected_f = np.where(feat_imp >= threshold)
print(selected_f)

(array([2, 3]),)


### Random Forest RFE to eliminate one or more than one features
Idea behind the Random Forest RFE method
Random forest Recursive Feature Elimination (RF-RFE) is to combine the power of Random Forest , n ensemble learning algorithm, with recursive Features Elimination method, a feature selection technique. RF-REF aims to find the most important features within a dataset by iteratrely fittng Random Forest models and eliminating the least important features based on their importance scores,

Step-by-step logic behind RF-RFE:

1. Build Random Forest Model:
    - A random forest model is ensemble deicsion tree. Each tree is built on a different subset of the data and features
    - Random Forest provides a way to rank the importance of features by eveluating how much they contribute to reducing impurity (e.g Gini) in the decision trees.


2. Calculate Feature Importances:
    - After training the Random Forest, you can calculate the importance score for each feature.
    - Feature importance is determine by how much the impurity (or another metric) is reduced by a feature when it is used for splitting nodes in the decision trees.

3. Rank and Eliminate Features:
    - RF-RFE starts by training a Random Forest model using all available features
    - It ranks the features based on their importance score
    - It eliminates the least important features and repeate the process.
    - At each iteration , the model trains on the reduced set of features, adn the feature importance are calculated.
4. Stop criterion:
    - The RF-RFE process continues iteratively , removing one or more feaatures at each step, until a predefined number of feeature is reduced or the model performance stablizes.
    
5. Cross validation and selection ⁉
    - During the process, corss-validation is often used to evaluate the models performance after each feature elimination step.
    - The optimal number of features is determine based on cross-validation results, where the model achieves the best performance.

    <b> Advantages of using RF+RFE </b>

    It captures both the individual features importance and the interactions between features that Random Forest inherently capture.

    Theis lead to more robust and accurate feature selection, especially when dealing with complex dataset.

    Note : RF_RFE is poerful technique , it might be computatiionally expensive for larger datasets. Additionally the choice of the numbe rof features to eliminate at each step, as well as the stopping criteria , can impact the results.
    



In [5]:
from sklearn.feature_selection import RFECV
from sklearn.model_selection import train_test_split
# Loat the dataset
iris = load_iris()
X,y = iris.data, iris.target

# we will split the data training and testing
train_X,test_X, train_y, test_y = train_test_split(X,y,random_state=42,test_size=.20)
rf_classi = RandomForestClassifier(n_estimators = 100, random_state=42)
# re-rfe
rfecv = RFECV(estimator=rf_classi, step = 1, cv = 5)

rfecv.fit(train_X,train_y)

print("optimal feature : %d" % rfecv.n_features_)
print("selected  features : %s" %str(rfecv.get_support))
print('Feature ranking: %s' % str(rfecv.ranking_))

# Transform the original data to the selected features
X_train_selected = rfecv.transform(train_X)
X_test_selected = rfecv.transform(test_X)


optimal feature : 2
selected  features : <bound method SelectorMixin.get_support of RFECV(cv=5, estimator=RandomForestClassifier(random_state=42))>
Feature ranking: [2 3 1 1]


we load the data <brr>
we split the data <br>
we create a base Random Forest classifier <br>
We create an RF-RFE selector ('RFECV') with the 'RandomForestClassifier' as the estimator.<br>
We fit RF_RFE selector on the trainin data.<br>
We print the optimal numnber of features, selected features mask('support_')<br> and feature ranking('ranking_')
We transform the original data into include only the selected features.





In [6]:
# apply grid search CV method to find the best estimators.
#

In [67]:
import pandas as pd
from sklearn.feature_selection import RFECV
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.ensemble import RandomForestClassifier

In [13]:
data=pd.read_csv('./heart.csv')

In [20]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   sex       303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trtbps    303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fbs       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalachh  303 non-null    int64  
 8   exng      303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slp       303 non-null    int64  
 11  caa       303 non-null    int64  
 12  thall     303 non-null    int64  
 13  output    303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


In [62]:
data[data['age']==52]

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
8     52    1   2     172   199    1        1       162     0      0.5    2   
45    52    1   1     120   325    0        1       172     0      0.2    2   
55    52    1   1     134   201    0        1       158     0      0.8    2   
62    52    1   3     118   186    0        0       190     0      0.0    1   
78    52    1   1     128   205    1        1       184     0      0.0    2   
83    52    1   3     152   298    1        1       178     0      1.2    1   
92    52    1   2     138   223    0        1       169     0      0.0    2   
97    52    1   0     108   233    1        1       147     0      0.1    2   
128   52    0   2     136   196    0        0       169     0      0.1    1   
205   52    1   0     128   255    0        1       161     1      0.0    2   
261   52    1   0     112   230    0        1       160     0      0.0    2   
275   52    1   0     125   212    0        1       168     0      1.0    2   
281   52    1   0     128   204    1        1       156     1      1.0    1   

     caa  thall  output  
8      0      3       1  
45     0      2       1  
55     1      2       1  
62     0      1       1  
78     0      2       1  
83     0      3       1  
92     4      2       1  
97     3      3       1  
128    0      2       1  
205    1      3       0  
261    1      2       0  
275    2      3       0  
281    0      0       0

In [39]:
X=data.drop('output',axis=1)
y=data['output']

In [41]:
train_X,test_X,train_y,test_y = train_test_split(X,y,test_size=.2,random_state=1)

Recursive feature elimination **with** cross validation

In [42]:
rd_class = RandomForestClassifier(n_estimators=100,random_state=42)
rfecv= RFECV(estimator=rd_class,step=1,cv=5)
rd_model=rfecv.fit(train_X,train_y)
pred= rd_model.predict(test_X)
print("Optimal Feature %d "  %rfecv.n_features_)
print("Selected Feature %s" % str(rfecv.get_support))
print("Feature ranking %s" %str(rfecv.ranking_))

Optimal Feature 11 
Selected Feature <bound method SelectorMixin.get_support of RFECV(cv=5, estimator=RandomForestClassifier(random_state=42))>
Feature ranking [1 1 1 1 1 3 2 1 1 1 1 1 1]


In [50]:
X_train_selected = rfecv.transform(train_X)
X_test_selected = rfecv.transform(test_X)
print(X_train_selected.shape)

(242, 11)


In [57]:
X_train_selected[0]

array([ 52.,   1.,   3., 118., 186., 190.,   0.,   0.,   1.,   0.,   1.])

Using GridsearchCV to find the best parameters for Random classifier

In [70]:
params= {
    'n_estimators':[50,25,75],
    'criterion' : ['gini','entropy'],
    'max_depth':[3],'min_samples_split':[2]
    }
grid=GridSearchCV(estimator=rd_class,param_grid=params,cv=5)
grid.fit(train_X,train_y)
print(grid.best_estimator_)

RandomForestClassifier(criterion='entropy', max_depth=3, n_estimators=75,
                       random_state=42)


In [78]:
rd_class1 = RandomForestClassifier(criterion='entropy', max_depth=3, n_estimators=75,
                       random_state=42)

rfecv1= RFECV(estimator=rd_class1,step=1,cv=5)
rd_model1=rfecv1.fit(train_X,train_y)
pred1= rd_model1.predict(test_X)
print("Optimal Feature %d "  % (rfecv1.n_features_))
print("Selected Feature %s" % str(rfecv1.get_support))
print("Feature ranking %s" % str(rfecv1.ranking_))

Optimal Feature 13 
Selected Feature <bound method SelectorMixin.get_support of RFECV(cv=5,
      estimator=RandomForestClassifier(criterion='entropy', max_depth=3,
                                       n_estimators=75, random_state=42))>
Feature ranking [1 1 1 1 1 1 1 1 1 1 1 1 1]


In [84]:
from sklearn.metrics import accuracy_score,confusion_matrix
print(accuracy_score(pred1,test_y))
print(confusion_matrix(pred1,test_y))

0.7704918032786885
[[20  4]
 [10 27]]
